Am 346   load an article
SkillsFundingAgency/das-campaign pull request #326
Opened 2021-06-21 15:06 UTC by sscaife

2021-06-23 21:10 UTC, dashton82 requested changes
Good stuff for first PR 🎉  Lots in there, few minor changes - also instead of 
`IsPassedAnObjectOfIHtmlControl....`
for things like test names, can it be 
`Is_Passed_An_Object_Of_IHtml_Control...`

2021-06-23 21:10 UTC, dashton82 commented on src/SFA.DAS.Campaign.UnitTests/Infrastructure/Api/Factory/WhenTableFactory.cs
> +        private static Item BuildTableControl()
Can this be moved to the bottom of the file please?

2021-06-23 21:10 UTC, dashton82 commented on src/SFA.DAS.Campaign.UnitTests/Infrastructure/Api/Factory/WhenUnorderedListControlFactory.cs
> +        private static Item BuildUnorderedListItemControl()
To the bottom of the file please

2021-06-23 21:10 UTC, dashton82 commented on src/SFA.DAS.Campaign.UnitTests/Infrastructure/Api/Queries/WhenGettingAnArticle.cs
> +            GetArticleQuery query, Page<Article> response, [Frozen]Mock<IApiClient> client, [Greedy] GetArticleQueryHandler handler)
Shouldnt need the [Greedy] attribute here

2021-06-23 21:10 UTC, dashton82 commented on src/SFA.DAS.Campaign.UnitTests/Infrastructure/Api/Queries/WhenGettingAnArticle.cs
> +            client.Setup(o => o.Get<Page<Article>>(It.IsAny<GetArticlesRequest>())).ReturnsAsync(response);
Can we check the actual values from the GetArticleQuery are being passed into the Setup to firm up the test a bit

2021-06-23 21:10 UTC, dashton82 commented on src/SFA.DAS.Campaign.UnitTests/Infrastructure/Api/WhenCallingGet.cs
> +            Mock<IHtmlControlAbstractFactory> controlFactory)
Based on earlier comment might need to undo this part passing in the`IHtmlControlAbstractFactory`

2021-06-23 21:10 UTC, dashton82 commented on src/SFA.DAS.Campaign.UnitTests/Web/Controllers/Article/WhenRequestingTheArticlePage.cs
> +            var controllerResult = await InstantiateController<ViewResult>(controller);
Can we make sure these tests are validating that the hub and slug values are being correctly passed to the mediator query

2021-06-23 21:10 UTC, dashton82 commented on src/SFA.DAS.Campaign.UnitTests/Web/Renderers/WhenParagraphControlRenderer.cs
> +        [Test, MoqAutoData]
This can probably just use the `[AutoData]` attribute

2021-06-23 21:10 UTC, dashton82 commented on src/SFA.DAS.Campaign.UnitTests/Web/Renderers/WhenHeadingControlRenderer.cs
> +        public void IsPassedAnObjectOfIHtmlControlThatIsOfParagraphThenSupportsContentReturnsTrue(Heading heading, HeadingControlRenderer renderer)
Can probably just use the `[AutoData]` attribute

2021-06-24 10:00 UTC, sscaife commented on src/SFA.DAS.Campaign.Domain/Content/ArticleSection.cs
> -        public string Slug { get; set; }
yeah we need to know what the parent page is, I'm thinking this should be content driven somehow, a page has a parent link and then we can pass this through in the payload from apim.

2021-06-24 10:12 UTC, sscaife commented on src/SFA.DAS.Campaign.Infrastructure/Api/ApiClient.cs
> +                return JsonConvert.DeserializeObject<TResponse>(json, new ArticleJsonConverter(_htmlControlAbstractFactory));
made a slight change so it's part of an if statement. For now it should suffice as we only have one converter. If that changes then it'll need looking at for a more suitable implementation

2021-06-24 10:15 UTC, sscaife commented on src/SFA.DAS.Campaign.Infrastructure/Api/Queries/GetArticleQueryHandler.cs
> +        private static Page<Article> CheckArticleForValidity(Page<Article> article)
removed

2021-06-24 10:21 UTC, sscaife commented on src/SFA.DAS.Campaign.Infrastructure/Api/Requests/GetArticlesRequest.cs
> +        public string GetUrl => $"article/{_hub}/{_slug}";
added a test

2021-06-24 10:55 UTC, dashton82 commented on src/SFA.DAS.Campaign.Domain/Content/ArticleSection.cs
> -        public string Slug { get; set; }
no probs - lets create a ticket to cover this 👌🏻

2021-06-24 10:55 UTC, dashton82 approved these changes

2021-06-30 09:38 UTC, sony-kotha commented
Testing completed

2021-06-30 09:38 UTC, merged

2021-06-30 09:38 UTC, sony-kotha commented
Testing completed