Qf 1274 allow small employers to calculate for more than ten apprentices
SkillsFundingAgency/das-campaign pull request #393
Opened 2023-04-11 14:32 UTC by PeterDavidWilliams

2023-04-12 09:09 UTC, ChrisJWoodcock requested changes

2023-04-12 09:09 UTC, ChrisJWoodcock commented on src/SFA.DAS.Campaign.UnitTests/Web/Controllers/Employer/WhenRequestingTheCalculateYourApprenticeshipFundingPage.cs
> +            Assert.IsFalse(_controller.ModelState.IsValid);
Should use either fluent assertions or the nunit asserts not mixed

2023-04-12 09:12 UTC, ChrisJWoodcock approved these changes

2023-04-13 12:49 UTC, SawNawDfE approved these changes
![image](https://user-images.githubusercontent.com/119664159/231763375-1ef7416a-2d26-4406-a624-869446abb01c.png)

2023-04-13 12:52 UTC, merged